pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }
        stage('build') {
            steps {
                sh """
                echo $WORKSPACE
                cd $WORKSPACE
                tar -zcvf tarfiles.\$(date +%F).tar.gz tarfiles
                """
            }
        }
    }
}
